# Generated by Django 2.2.4 on 2019-09-16 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Tokens',
        ),
    ]
